# Generated by Django 2.2.3 on 2019-07-15 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentary', '0003_auto_20190715_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comments',
        ),
    ]
