# Generated by Django 2.2.2 on 2019-06-12 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('boyNum', models.IntegerField()),
                ('girlNum', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sex', models.BooleanField()),
                ('age', models.IntegerField()),
                ('content', models.CharField(max_length=40)),
                ('isDelete', models.BooleanField(default=False)),
                ('grade', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='myApp.Grade')),
            ],
        ),
    ]
