# Generated by Django 2.2.2 on 2019-06-13 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
