# Generated by Django 2.2.2 on 2019-06-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20190613_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.IntegerField(choices=[(0, '女'), (0, '男')], default=1),
        ),
    ]
