# Generated by Django 2.2.3 on 2019-07-15 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='isDelete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='isDelete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='isDelete',
            new_name='is_delete',
        ),
    ]
