# Generated by Django 2.2.2 on 2019-06-30 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
